# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: joshsj
description:
  "I'm a spirited software developer from Manchester seeking a job in full stack
  web development. Any tech stack is a good tech stack, but .NET, Vue and SQL is
  my jam."
author: Joshua Sexton-Jones
language: en
timezone: Europe/London

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://joshsj.github.io
permalink: :year/:month/:day/:title/
pretty_urls:
  trailing_index: false
  trailing_html: false

post_asset_folder: true
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# moment.js settings
date_format: MMMM Do, YYYY
time_format: HH:mm
updated_option: "date"

# plugins
theme: joshsj
marked:
  breaks: false
  gfm: true
  smartypants: true

sitemap:
  tags: true
  categories: false

# lib assets
lib_asset_root: /../node_modules
